import { StyleSheet } from 'react-native';
import { themeColors } from '../theme/colors';

export const allStyles = StyleSheet.create({
  container: {
    borderRadius: 6,
    backgroundColor: themeColors.surface,
    borderWidth: 2,
    borderColor: themeColors.surfaceMuted,
    padding: 0,
    minHeight: 320,
    height: '100%',
  },
  sectionContainer: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    paddingVertical: 5,
    paddingHorizontal: 5,
  }
  ,
  filterCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    padding: 0,
    marginBottom: 10,
  },
  sectionTitle: {
    color: themeColors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  sectionSubtitle: {
    color: themeColors.textSecondary,
    fontSize: 12,
    marginBottom: 10,
  },
  selectedFilterSummary: {
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  accordionHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    gap: 10,
  },
  accordionHeaderTextWrap: {
    flex: 1,
  },
  accordionContent: {
    marginTop: 8,
    borderTopWidth: 1,
    borderTopColor: themeColors.border,
    backgroundColor: themeColors.surfaceMuted,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 8,
  },
  filterSummaryRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    marginBottom: 6,
  },
  filterSummaryValueRow: {
    borderWidth: 1,
    borderColor: themeColors.successBorder,
    backgroundColor: themeColors.successSurface,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 7,
    gap: 2,
  },
  sectionDivider: {
    backgroundColor: themeColors.border,
    height: 1,
    marginVertical: 10,
  },
  selectedFilterLabel: {
    color: themeColors.textSecondary,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    fontWeight: '700',
  },
  selectedFilterValue: {
    color: themeColors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  selectedFilterDates: {
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  dateRow: {
    flexDirection: 'row',
    gap: 8,
  },
  dateField: {
    flex: 1,
  },
  label: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 6,
    marginTop: 8,
  },
  input: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    color: themeColors.textPrimary,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 13,
  },
  datePickerButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  datePickerText: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  filterButton: {
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: themeColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  filterButtonText: {
    color: themeColors.textOnBrand,
    fontWeight: '700',
  },
  loadingWrap: {
    paddingVertical: 14,
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadingText: {
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  errorText: {
    color: '#B42318',
    fontSize: 12,
    marginBottom: 8,
  },
  list: {},
  listContent: {
    gap: 10,
    paddingBottom: 108,
    paddingHorizontal: 2,
  },
  taskCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: themeColors.border,
    padding: 13,
    backgroundColor: themeColors.surface,
  },
  taskCardSelected: {
    borderColor: themeColors.primary,
    backgroundColor: themeColors.successSurface,
  },
  taskTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    gap: 8,
  },
  statusActionsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  taskName: {
    color: themeColors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
  },
  taskNameWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  selectionIndicator: {
    width: 24,
    height: 24,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: themeColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeColors.surface,
  },
  selectionIndicatorSelected: {
    borderColor: themeColors.primary,
    backgroundColor: themeColors.primary,
  },
  statusBadge: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  statusBadgeText: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.3,
  },
  statusBadgeNotStarted: {
    backgroundColor: themeColors.statusNotStartedSurface,
  },
  statusBadgeNotStartedText: {
    color: themeColors.statusNotStartedText,
  },
  statusBadgeInProgress: {
    backgroundColor: themeColors.statusInProgressSurface,
  },
  statusBadgeInProgressText: {
    color: themeColors.statusInProgressText,
  },
  statusBadgeCompleted: {
    backgroundColor: themeColors.statusCompletedSurface,
  },
  statusBadgeCompletedText: {
    color: themeColors.statusCompletedText,
  },
  headerIconAction: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: themeColors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSecondaryIconAction: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskServiceText: {
    color: themeColors.textSecondary,
    fontSize: 13,
    marginBottom: 8,
  },
  taskMetaRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  taskMetaItem: {
    flex: 1,
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  taskMetaItemRight: {
    textAlign: 'right',
  },
  taskActions: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  actionButton: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 9,
    backgroundColor: themeColors.secondary,
    alignItems: 'center',
  },
  actionButtonText: {
    color: themeColors.textOnBrand,
    fontSize: 12,
    fontWeight: '700',
  },
  secondaryActionButton: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: themeColors.border,
    alignItems: 'center',
    backgroundColor: themeColors.surfaceMuted,
  },
  secondaryActionButtonText: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  disabledButton: {
    opacity: 0.6,
  },
  disabledSecondaryButton: {
    opacity: 0.5,
  },
  emptyState: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    paddingVertical: 22,
    paddingHorizontal: 14,
    alignItems: 'center',
    gap: 6,
  },
  containerCard: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surfaceMuted,
    paddingVertical: 10,
    paddingHorizontal: 12,
  },
  emptyText: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  emptySubText: {
    color: themeColors.textSecondary,
    fontSize: 12,
    textAlign: 'center',
  },
  modalScreen: {
    flex: 1,
    backgroundColor: themeColors.appBackground,
  },
  modalHeader: {
    paddingTop: 52,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: themeColors.surface,
  },
  modalTitle: {
    color: themeColors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  closeText: {
    color: themeColors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  modalBody: {
    padding: 14,
    gap: 8,
  },
  modalContent: {
    flex: 1,
  },
  modalScroll: {
    flex: 1,
  },
  modalBodyWithFooter: {
    padding: 14,
    gap: 8,
    paddingBottom: 20,
  },
  modalFooter: {
    borderTopWidth: 1,
    borderTopColor: themeColors.border,
    backgroundColor: themeColors.surface,
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 14,
  },
  modalFooterButton: {
    marginTop: 0,
  },
  typeRow: {
    gap: 8,
    paddingVertical: 4,
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  typeChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: themeColors.surface,
  },
  typeChipActive: {
    borderColor: themeColors.primary,
    backgroundColor: themeColors.successSurface,
  },
  typeChipText: {
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  typeChipTextActive: {
    color: themeColors.primary,
    fontWeight: '700',
  },
  textArea: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  fileNameText: {
    color: themeColors.textSecondary,
    fontSize: 12,
    marginTop: 8,
  },
  filterHelperText: {
    color: themeColors.textSecondary,
    fontSize: 11,
    lineHeight: 15,
  },
  filterChipGroup: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 6,
    columnGap: 6,
  },
  filterChip: {
    flexBasis: '31.7%',
    maxWidth: '31.7%',
    minHeight: 34,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    paddingHorizontal: 8,
    paddingVertical: 6,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterChipSelected: {
    borderColor: themeColors.primary,
    backgroundColor: themeColors.successSurface,
  },
  filterChipText: {
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  filterChipTextSelected: {
    color: themeColors.primary,
  },
  radioGroup: {
    gap: 8,
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: themeColors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterSelected: {
    borderColor: themeColors.primary,
  },
  radioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: themeColors.primary,
  },
  radioLabel: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  customRangeWrap: {
    gap: 6,
  },
  customRangeRow: {
    gap: 8,
  },
  customRangeField: {
    width: '100%',
  },
  dialogActions: {
    marginTop: 2,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  filterActionButton: {
    width: 38,
    height: 38,
    borderRadius: 19,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterActionButtonPrimary: {
    backgroundColor: themeColors.primary,
    borderColor: themeColors.primary,
  },
  dialogCancelButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingHorizontal: 12,
    paddingVertical: 7,
    backgroundColor: themeColors.surface,
  },
  dialogCancelText: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  dialogApplyButton: {
    borderRadius: 8,
    backgroundColor: themeColors.primary,
    paddingHorizontal: 14,
    paddingVertical: 7,
  },
  dialogApplyButtonDisabled: {
    opacity: 0.55,
  },
  dialogApplyText: {
    color: themeColors.textOnBrand,
    fontSize: 13,
    fontWeight: '700',
  },
  filterErrorText: {
    color: themeColors.warningText,
    backgroundColor: themeColors.warningSurface,
    borderWidth: 1,
    borderColor: themeColors.warningBorder,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 8,
    fontSize: 12,
    lineHeight: 17,
  },
  pickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  pickerModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  pickerModalCard: {
    borderRadius: 14,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
  },
  pickerModalTitle: {
    color: themeColors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  pickerModalActions: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
});

export const taskDetailsPanelStyles = StyleSheet.create({
  panelRoot: {
    flex: 1,
    position: 'relative',
  },
  loadingWrap: {
    paddingVertical: 14,
  },
  loadingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  loadingText: {
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  errorText: {
    color: '#B42318',
    fontSize: 12,
    marginBottom: 8,
  },
  scrollContent: {
    gap: 10,
    paddingBottom: 24,
  },
  headerCard: {
    borderRadius: 12,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 12,
  },
  statusChip: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusChipNotStarted: {
    backgroundColor: themeColors.statusNotStartedSurface,
  },
  statusChipInProgress: {
    backgroundColor: themeColors.statusInProgressSurface,
  },
  statusChipCompleted: {
    backgroundColor: themeColors.statusCompletedSurface,
  },
  statusChipText: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  statusChipTextNotStarted: {
    color: themeColors.statusNotStartedText,
  },
  statusChipTextInProgress: {
    color: themeColors.statusInProgressText,
  },
  statusChipTextCompleted: {
    color: themeColors.statusCompletedText,
  },
  titleBlock: {
    gap: 2,
    flex: 1,
    paddingRight: 8,
  },
  headerEyebrow: {
    color: themeColors.textSecondary,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
    fontWeight: '700',
  },
  title: {
    color: themeColors.textPrimary,
    fontSize: 17,
    fontWeight: '800',
  },
  subTitle: {
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '500',
  },
  metaGrid: {
    gap: 8,
  },
  metaRowCard: {
    gap: 10,
    borderRadius: 10,
    backgroundColor: '#F7F8F8',
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  metaTwoColRow: {
    flexDirection: 'row',
    gap: 14,
  },
  metaFieldBlock: {
    flex: 1,
    gap: 2,
  },
  metaLabel: {
    color: themeColors.textSecondary,
    fontSize: 11,
    fontWeight: '500',
  },
  metaText: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
  },
  metaRowCardHalf: {
    flex: 1,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  metaKey: {
    flex: 1,
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  metaValue: {
    flex: 1.25,
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'right',
  },
  taskStatusActions: {
    marginTop: 14,
    flexDirection: 'row',
    gap: 10,
  },
  taskStatusActionButton: {
    borderRadius: 10,
    backgroundColor: themeColors.primary,
    paddingHorizontal: 12,
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  taskStatusActionButtonFull: {
    width: '100%',
  },
  taskStatusActionButtonHalf: {
    flex: 1,
  },
  taskStatusActionButtonSecondary: {
    borderRadius: 10,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: '#DDD9D1',
    paddingHorizontal: 12,
    height: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  taskStatusActionButtonDisabled: {
    opacity: 0.6,
  },
  taskStatusActionText: {
    color: themeColors.textOnBrand,
    fontSize: 14,
    fontWeight: '700',
  },
  taskStatusActionTextSecondary: {
    color: '#55585C',
    fontSize: 14,
    fontWeight: '700',
  },
  sectionCard: {
    borderRadius: 12,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 10,
  },
  sectionHeading: {
    color: themeColors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  sectionHint: {
    color: themeColors.textSecondary,
    fontSize: 12,
    lineHeight: 17,
  },
  sectionCountBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: themeColors.successBorder,
    backgroundColor: themeColors.successSurface,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  sectionCountText: {
    color: themeColors.primary,
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  sectionCountBadgeCompact: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: themeColors.successSurface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sectionCountTextCompact: {
    color: themeColors.primary,
    fontSize: 12,
    fontWeight: '700',
  },
  infoCard: {
    borderRadius: 10,
    backgroundColor: '#F7F8F8',
    padding: 12,
    gap: 10,
  },
  infoIdentityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    marginBottom: 2,
  },
  infoAvatarCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#EFF2F1',
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoAvatarText: {
    color: '#5F6466',
    fontSize: 13,
    fontWeight: '700',
  },
  infoName: {
    color: themeColors.textPrimary,
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '800',
  },
  infoTwoColGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    columnGap: 14,
    rowGap: 8,
  },
  infoTwoColCell: {
    width: '48%',
    gap: 2,
  },
  infoBlockLabel: {
    color: themeColors.textSecondary,
    fontSize: 11,
    fontWeight: '500',
  },
  infoBlockValue: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 17,
  },
  infoValue: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '500',
  },
  infoKeyValueRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  infoKey: {
    flex: 1,
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  infoVal: {
    flex: 1.3,
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
  },
  recordsList: {
    gap: 8,
  },
  recordsHeaderAction: {
    borderRadius: 999,
    backgroundColor: themeColors.primary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  recordsHeaderActionText: {
    color: themeColors.textOnBrand,
    fontSize: 12,
    fontWeight: '700',
  },
  fabOverlay: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    paddingRight: 16,
    paddingBottom: 16,
  },
  fabBackdrop: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    backgroundColor: themeColors.backDrop,
  },
  fabOptionsWrap: {
    marginBottom: 10,
    alignItems: 'flex-end',
    gap: 8,
    zIndex: 1,
  },
  fabOptionButton: {
    borderRadius: 999,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingVertical: 9,
    paddingHorizontal: 14,
    minWidth: 148,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 4,
  },
  fabOptionText: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  fabButton: {
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: themeColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
    shadowColor: '#000000',
    shadowOpacity: 0.24,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 10,
    elevation: 6,
  },
  fabButtonText: {
    color: themeColors.textOnBrand,
    fontSize: 30,
    lineHeight: 32,
    fontWeight: '400',
    marginTop: -1,
  },
  recordCard: {
    position: 'relative',
    zIndex: 1,
    borderRadius: 10,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    padding: 10,
  },
  recordCardActiveLayer: {
    zIndex: 12,
    elevation: 8,
  },
  recordTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  recordTitle: {
    flex: 1,
    color: themeColors.textPrimary,
    fontSize: 14,
    fontWeight: '800',
  },
  recordTypeChip: {
    alignSelf: 'flex-start',
    marginTop: 4,
    borderRadius: 999,
    backgroundColor: themeColors.surfaceMuted,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  recordTypeChipText: {
    color: themeColors.textSecondary,
    fontSize: 11,
    fontWeight: '700',
  },
  recordBody: {
    gap: 4,
    marginTop: 7,
  },
  recordMeta: {
    color: themeColors.textSecondary,
    fontSize: 12,
  },
  recordMetaStrong: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  recordStatusIconWrap: {
    width: 24,
    height: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  recordActions: {
    marginTop: 10,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  actionPill: {
    borderRadius: 10,
    backgroundColor: themeColors.primary,
    paddingHorizontal: 11,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionPillSecondary: {
    borderRadius: 10,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingHorizontal: 11,
    paddingVertical: 7,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionPillText: {
    color: themeColors.textOnBrand,
    fontSize: 12,
    fontWeight: '700',
  },
  actionPillTextSecondary: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  actionIconButtonSecondary: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionIconButtonPrimary: {
    width: 34,
    height: 34,
    borderRadius: 17,
    backgroundColor: themeColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionOverflowWrap: {
    position: 'relative',
  },
  actionOverflowMenu: {
    position: 'absolute',
    right: 0,
    top: 38,
    zIndex: 5,
    minWidth: 132,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    paddingVertical: 4,
    shadowColor: '#000000',
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 4,
  },
  actionOverflowItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  actionOverflowItemText: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  emptyState: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    paddingVertical: 20,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  emptyText: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    textAlign: 'center',
  },
  previewScreen: {
    flex: 1,
    backgroundColor: themeColors.appBackground,
  },
  previewHeader: {
    paddingTop: 52,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: themeColors.surface,
  },
  previewTitle: {
    color: themeColors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  previewClose: {
    color: themeColors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  previewBody: {
    padding: 14,
    gap: 8,
  },
  previewText: {
    color: themeColors.textPrimary,
    fontSize: 13,
    lineHeight: 20,
  },
})