import { StyleSheet } from 'react-native';
import { themeColors } from '../theme/colors';

export const allStyles = StyleSheet.create({
  container: {
    borderRadius: 6,
    backgroundColor: themeColors.surface,
    borderWidth: 2,
    borderColor: themeColors.primary,
    padding: 0,
    minHeight: 320,
  },
  filterCard: {
    borderTopEndRadius: 4,
    borderTopStartRadius: 4,
    borderWidth: 1,
    borderColor: themeColors.primary,
    backgroundColor: themeColors.primary,
    padding: 0,
    marginBottom: 10,
  },
  sectionTitle: {
    color: themeColors.textPrimary,
    fontSize: 17,
    fontWeight: '700',
  },
  sectionSubtitle: {
    color: themeColors.textSecondary,
    fontSize: 12,
    marginBottom: 10,
  },
  selectedFilterSummary: {
    borderRadius: 10,
    borderColor: themeColors.border,
    backgroundColor: themeColors.primary,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  accordionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
  },
  accordionHeaderTextWrap: {
    flex: 1,
  },
  accordionContent: {
    marginTop: 10,
    borderTopWidth: 1,
    borderTopColor: themeColors.border,
    backgroundColor: themeColors.surfaceMuted,
    padding: 10,
  },
  selectedFilterLabel: {
    color: themeColors.textOnBrand,
    fontSize: 11,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginTop: 4,
    marginBottom: 4,
    marginLeft: 4,
  },
  selectedFilterValue: {
    color: themeColors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  selectedFilterDates: {
    color: themeColors.textOnBrand,
    fontSize: 12,
  },
  dateRow: {
    flexDirection: 'row',
    gap: 8,
  },
  dateField: {
    flex: 1,
  },
  label: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
    marginBottom: 6,
    marginTop: 8,
  },
  input: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    color: themeColors.textPrimary,
    paddingHorizontal: 10,
    paddingVertical: 10,
    fontSize: 13,
  },
  datePickerButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surface,
    paddingHorizontal: 10,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  datePickerText: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  filterButton: {
    marginTop: 10,
    borderRadius: 10,
    backgroundColor: themeColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
  },
  filterButtonText: {
    color: themeColors.textOnBrand,
    fontWeight: '700',
  },
  loadingWrap: {
    paddingVertical: 10,
  },
  errorText: {
    color: '#B42318',
    fontSize: 12,
    marginBottom: 8,
  },
  list: {},
  listContent: {
    gap: 10,
    paddingBottom: 108,
    paddingHorizontal: 10,
  },
  taskCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColors.border,
    padding: 12,
    backgroundColor: themeColors.surface,
  },
  taskCardSelected: {
    borderColor: themeColors.primary,
    backgroundColor: themeColors.surfaceMuted,
  },
  taskTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 6,
    gap: 8,
  },
  statusActionsWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  taskName: {
    color: themeColors.textPrimary,
    fontSize: 14,
    fontWeight: '700',
  },
  taskNameWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  selectionIndicator: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: themeColors.border,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: themeColors.surface,
  },
  selectionIndicatorSelected: {
    borderColor: themeColors.primary,
    backgroundColor: themeColors.primary,
  },
  statusBadge: {
    fontSize: 11,
    fontWeight: '800',
    textTransform: 'uppercase',
  },
  headerIconAction: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: themeColors.secondary,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerSecondaryIconAction: {
    width: 26,
    height: 26,
    borderRadius: 13,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surfaceMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  taskMeta: {
    color: themeColors.textSecondary,
    fontSize: 12,
    marginBottom: 2,
  },
  taskActions: {
    marginTop: 10,
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  actionButton: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 9,
    backgroundColor: themeColors.secondary,
    alignItems: 'center',
  },
  actionButtonText: {
    color: themeColors.textOnBrand,
    fontSize: 12,
    fontWeight: '700',
  },
  secondaryActionButton: {
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderRadius: 9,
    borderWidth: 1,
    borderColor: themeColors.border,
    alignItems: 'center',
    backgroundColor: themeColors.surfaceMuted,
  },
  secondaryActionButtonText: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  disabledButton: {
    opacity: 0.6,
  },
  disabledSecondaryButton: {
    opacity: 0.5,
  },
  emptyState: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surfaceMuted,
    paddingVertical: 18,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  emptyText: {
    color: themeColors.textSecondary,
    fontSize: 12,
  },
  modalScreen: {
    flex: 1,
    backgroundColor: themeColors.appBackground,
  },
  modalHeader: {
    paddingTop: 52,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: themeColors.surface,
  },
  modalTitle: {
    color: themeColors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  closeText: {
    color: themeColors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  modalBody: {
    padding: 14,
    gap: 8,
  },
  typeRow: {
    gap: 8,
    paddingVertical: 4,
  },
  typeChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: themeColors.surface,
  },
  typeChipActive: {
    borderColor: themeColors.secondary,
    backgroundColor: '#FFF1E8',
  },
  typeChipText: {
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '600',
  },
  typeChipTextActive: {
    color: themeColors.secondary,
    fontWeight: '700',
  },
  textArea: {
    minHeight: 90,
    textAlignVertical: 'top',
  },
  fileNameText: {
    color: themeColors.textSecondary,
    fontSize: 12,
    marginTop: 8,
  },
  radioGroup: {
    gap: 8,
  },
  radioRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  radioOuter: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: themeColors.border,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioOuterSelected: {
    borderColor: themeColors.primary,
  },
  radioInner: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: themeColors.primary,
  },
  radioLabel: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
  },
  customRangeWrap: {
    marginTop: 10,
    gap: 4,
  },
  dialogActions: {
    marginTop: 14,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
  dialogCancelButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: themeColors.surface,
  },
  dialogCancelText: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
  },
  dialogApplyButton: {
    borderRadius: 10,
    backgroundColor: themeColors.primary,
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  dialogApplyText: {
    color: themeColors.textOnBrand,
    fontSize: 13,
    fontWeight: '700',
  },
  pickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.2)',
    justifyContent: 'center',
    paddingHorizontal: 18,
  },
  pickerModalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  pickerModalCard: {
    borderRadius: 14,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 10,
  },
  pickerModalTitle: {
    color: themeColors.textPrimary,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 4,
  },
  pickerModalActions: {
    marginTop: 4,
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 8,
  },
});

export const taskDetailsPanelStyles = StyleSheet.create({
  panelRoot: {
    flex: 1,
    position: 'relative',
  },
  loadingWrap: {
    paddingVertical: 10,
  },
  errorText: {
    color: '#B42318',
    fontSize: 12,
    marginBottom: 8,
  },
  scrollContent: {
    gap: 12,
    paddingBottom: 24,
  },
  headerCard: {
    borderRadius: 14,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
  },
  statusRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
    marginBottom: 12,
  },
  statusChip: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  statusChipText: {
    color: themeColors.textOnBrand,
    fontSize: 12,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  titleBlock: {
    gap: 4,
  },
  title: {
    color: themeColors.textPrimary,
    fontSize: 20,
    fontWeight: '800',
  },
  subTitle: {
    color: themeColors.textSecondary,
    fontSize: 12,
  },
  metaGrid: {
    gap: 8,
  },
  metaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  metaKey: {
    flex: 1,
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  metaValue: {
    flex: 1.25,
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
  },
  sectionCard: {
    borderRadius: 14,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    marginBottom: 12,
  },
  sectionHeading: {
    color: themeColors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  sectionHint: {
    color: themeColors.textSecondary,
    fontSize: 12,
  },
  infoCard: {
    borderRadius: 12,
    backgroundColor: themeColors.surfaceMuted,
    padding: 12,
    gap: 8,
  },
  infoName: {
    color: themeColors.textPrimary,
    fontSize: 16,
    fontWeight: '800',
  },
  infoValue: {
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '500',
  },
  infoKeyValueRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  infoKey: {
    flex: 1,
    color: themeColors.textSecondary,
    fontSize: 12,
    fontWeight: '700',
  },
  infoVal: {
    flex: 1.3,
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'right',
  },
  recordsList: {
    gap: 10,
  },
  recordsHeaderAction: {
    borderRadius: 999,
    backgroundColor: themeColors.primary,
    paddingHorizontal: 10,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  recordsHeaderActionText: {
    color: themeColors.textOnBrand,
    fontSize: 12,
    fontWeight: '700',
  },
  fabOverlay: {
    position: 'absolute',
    right: 16,
    bottom: 16,
    left: 16,
    alignItems: 'flex-end',
  },
  fabBackdrop: {
    position: 'absolute',
    top: -500,
    right: -500,
    bottom: -500,
    left: -500,
  },
  fabOptionsWrap: {
    marginBottom: 10,
    alignItems: 'flex-end',
    gap: 8,
  },
  fabOptionButton: {
    borderRadius: 999,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingVertical: 9,
    paddingHorizontal: 14,
    minWidth: 148,
    alignItems: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.16,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    elevation: 4,
  },
  fabOptionText: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  fabButton: {
    width: 56,
    height: 56,
    borderRadius: 999,
    backgroundColor: themeColors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000000',
    shadowOpacity: 0.24,
    shadowOffset: { width: 0, height: 6 },
    shadowRadius: 10,
    elevation: 6,
  },
  fabButtonText: {
    color: themeColors.textOnBrand,
    fontSize: 30,
    lineHeight: 32,
    fontWeight: '400',
    marginTop: -1,
  },
  recordCard: {
    borderRadius: 12,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    padding: 12,
  },
  recordTopRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 10,
  },
  recordTitle: {
    flex: 1,
    color: themeColors.textPrimary,
    fontSize: 13,
    fontWeight: '800',
  },
  recordBody: {
    gap: 4,
    marginTop: 8,
  },
  recordMeta: {
    color: themeColors.textSecondary,
    fontSize: 12,
  },
  recordMetaStrong: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  recordActions: {
    marginTop: 12,
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  actionPill: {
    borderRadius: 999,
    backgroundColor: themeColors.primary,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionPillSecondary: {
    borderRadius: 999,
    backgroundColor: themeColors.surface,
    borderWidth: 1,
    borderColor: themeColors.border,
    paddingHorizontal: 12,
    paddingVertical: 8,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  actionPillText: {
    color: themeColors.textOnBrand,
    fontSize: 12,
    fontWeight: '700',
  },
  actionPillTextSecondary: {
    color: themeColors.textPrimary,
    fontSize: 12,
    fontWeight: '700',
  },
  emptyState: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: themeColors.border,
    backgroundColor: themeColors.surfaceMuted,
    paddingVertical: 18,
    paddingHorizontal: 12,
    alignItems: 'center',
  },
  emptyText: {
    color: themeColors.textSecondary,
    fontSize: 12,
    textAlign: 'center',
  },
  previewScreen: {
    flex: 1,
    backgroundColor: themeColors.appBackground,
  },
  previewHeader: {
    paddingTop: 52,
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: themeColors.border,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: themeColors.surface,
  },
  previewTitle: {
    color: themeColors.textPrimary,
    fontSize: 16,
    fontWeight: '700',
  },
  previewClose: {
    color: themeColors.primary,
    fontSize: 14,
    fontWeight: '700',
  },
  previewBody: {
    padding: 14,
    gap: 8,
  },
  previewText: {
    color: themeColors.textPrimary,
    fontSize: 13,
    lineHeight: 20,
  },
});
