export const themeColors = {
  primary: '#06ADAF',
  secondary: '#FF914D',
  textOnBrand: '#FFFFFF',
  appBackground: '#F2FBFB',
  surface: '#FFFFFF',
  surfaceMuted: '#E9F7F7',
  border: '#CBE7E7',
  textPrimary: '#1F2D2F',
  textSecondary: '#5C7476',
  pressed: '#03989A',
  warningSurface: '#FFF4EC',
  warningBorder: '#FFD1B2',
  warningText: '#8A4B22',
  successSurface: '#E6FAF7',
  successBorder: '#7EDDD0',
  backDrop: '#9adedf67',
  errorSurface: '#FDEEEE',
  errorBorder: '#F3B6B6',
} as const;
